 
  const Industry = [
    { name: "Education", value: "Education" },
    { name: "Education Management", value: "Education Management" },
    { name: "E-Learning", value: "E-Learning" },
    { name: "Higher Education", value: "Higher Education" },
    { name: "Primary/Secondary Education", value: "Primary/Secondary Education" },
    { name: "Research", value: "Research" },
    { name: "Construction", value: "Construction" },
    { name: "Building Materials", value: "Building Materials" },
    { name: "Civil Engineering", value: "Civil Engineering" },
    { name: "Design", value: "Design" },
    { name: "Architecture & Planning", value: "Architecture & Planning" },
    { name: "Graphic Design", value: "Graphic Design" },
    { name: "Corporate Services", value: "Corporate Services" },
    { name: "Accounting", value: "Accounting" },
    { name: "Business Supplies & Equipment", value: "Business Supplies & Equipment" },
    { name: "Environmental Services", value: "Environmental Services" },
    { name: "Events Services", value: "Events Services" },
    { name: "Executive Office", value: "Executive Office" },
    { name: "Facilities Services", value: "Facilities Services" },
    { name: "Human Resources", value: "Human Resources" },
    { name: "Information Services", value: "Information Services" },
    { name: "Management Consulting", value: "Management Consulting" },
    { name: "Outsourcing/Offshoring", value: "Outsourcing/Offshoring" },
    { name: "Professional Training & Coaching", value: "Professional Training & Coaching" },
    { name: "Security & Investigations", value: "Security & Investigations" },
    { name: "Staffing & Recruiting", value: "Staffing & Recruiting" },
    { name: "Retail", value: "Retail" },
    { name: "Supermarkets", value: "Supermarkets" },
    { name: "Wholesale", value: "Wholesale" },
    { name: "Energy & Mining", value: "Energy & Mining" },
    { name: "Mining & Metals", value: "Mining & Metals" },
    { name: "Oil & Energy", value: "Oil & Energy" },
    { name: "Utilities", value: "Utilities" },
    { name: "Manufacturing", value: "Manufacturing" },
    { name: "Automotive", value: "Automotive" },
    { name: "Aviation & Aerospace", value: "Aviation & Aerospace" },
    { name: "Electrical & Electronic Manufacturing", value: "Electrical & Electronic Manufacturing" },
    { name: "Food Production", value: "Food Production" },
    { name: "Glass, Ceramics & Concrete", value: "Glass, Ceramics & Concrete" },
    { name: "Industrial Automation", value: "Industrial Automation" },
    { name: "Machinery", value: "Machinery" },
    { name: "Mechanical or Industrial Engineering", value: "Mechanical or Industrial Engineering" },
    { name: "Packaging & Containers", value: "Packaging & Containers" },
    { name: "Paper & Forest Products", value: "Paper & Forest Products" },
    { name: "Plastics", value: "Plastics" },
    { name: "Railroad Manufacture", value: "Railroad Manufacture" },
    { name: "Renewables & Environment", value: "Renewables & Environment" },
    { name: "Shipbuilding", value: "Shipbuilding" },
    { name: "Textiles", value: "Textiles" },
    { name: "Finance", value: "Finance" },
    { name: "Banking", value: "Banking" },
    { name: "Capital Markets", value: "Capital Markets" },
    { name: "Financial Services", value: "Financial Services" },
    { name: "Insurance", value: "Insurance" },
    { name: "Investment Banking", value: "Investment Banking" },
    { name: "Investment Management", value: "Investment Management" },
    { name: "Venture Capital & Private Equity", value: "Venture Capital & Private Equity" },
    { name: "Recreation & Travel", value: "Recreation & Travel" },
    { name: "Airlines/Aviation", value: "Airlines/Aviation" },
    { name: "Gambling & Casinos", value: "Gambling & Casinos" },
    { name: "Hospitality", value: "Hospitality" },
    { name: "Leisure, Travel & Tourism", value: "Leisure, Travel & Tourism" },
    { name: "Restaurants", value: "Restaurants" },
    { name: "Recreational Facilities & Services", value: "Recreational Facilities & Services" },
    { name: "Sports", value: "Sports" },
    { name: "Arts", value: "Arts" },
    { name: "Arts & Crafts", value: "Arts & Crafts" },
    { name: "Fine Art", value: "Fine Art" },
    { name: "Performing Arts", value: "Performing Arts" },
    { name: "Photography", value: "Photography" },
    { name: "Health Care", value: "Health Care" },
    { name: "Biotechnology", value: "Biotechnology" },
    { name: "Hospital & Health Care", value: "Hospital & Health Care" },
    { name: "Medical Device", value: "Medical Device" },
    { name: "Medical Practice", value: "Medical Practice" },
    { name: "Mental Health Care", value: "Mental Health Care" },
    { name: "Pharmaceuticals", value: "Pharmaceuticals" },
    { name: "Veterinary", value: "Veterinary" },
    { name: "Hardware & Networking", value: "Hardware & Networking" },
    { name: "Computer Hardware", value: "Computer Hardware" },
    { name: "Computer Networking", value: "Computer Networking" },
    { name: "Nanotechnologie", value: "Nanotechnologie" },
    { name: "Semiconductors", value: "Semiconductors" },
    { name: "Telecommunications", value: "Telecommunications" },
    { name: "Wireless", value: "Wireless" },
    { name: "Real Estate", value: "Real Estate" },
    { name: "Commercial Real Estate", value: "Commercial Real Estate" },
    { name: "Legal", value: "Legal" },
    { name: "Alternative Dispute Resolution", value: "Alternative Dispute Resolution" },
    { name: "Law Practice", value: "Law Practice" },
    { name: "Legal Services", value: "Legal Services" },
    { name: "Consumer Goods", value: "Consumer Goods" },
    { name: "Apparel & Fashion", value: "Apparel & Fashion" },
    { name: "Consumer Electronics", value: "Consumer Electronics" },
    { name: "Consumer Services", value: "Consumer Services" },
    { name: "Cosmetics", value: "Cosmetics" },
    { name: "Food & Beverages", value: "Food & Beverages" },
    { name: "Furniture", value: "Furniture" },
    { name: "Luxury Goods & Jewelry", value: "Luxury Goods & Jewelry" },
    { name: "Sporting Goods", value: "Sporting Goods" },
    { name: "Tobacco", value: "Tobacco" },
    { name: "Wine and Spirits", value: "Wine and Spirits" },
    { name: "Agriculture", value: "Agriculture" },
    { name: "Dairy", value: "Dairy" },
    { name: "Farming", value: "Farming" },
    { name: "Fishery", value: "Fishery" },
    { name: "Ranching", value: "Ranching" },
    { name: "Media & Communications", value: "Media & Communications" },
    { name: "Market Research", value: "Market Research" },
    { name: "Marketing & Advertising", value: "Marketing & Advertising" },
    { name: "Newspapers", value: "Newspapers" },
    { name: "Online Media", value: "Online Media" },
    { name: "Printing", value: "Printing" },
    { name: "Public Relations & Communications", value: "Public Relations & Communications" },
    { name: "Publishing", value: "Publishing" },
    { name: "Translation & Localization", value: "Translation & Localization" },
    { name: "Writing & Editing", value: "Writing & Editing" },
    { name: "Nonprofit", value: "Nonprofit" },
    { name: "Civic & Social Organization", value: "Civic & Social Organization" },
    { name: "Fundraising", value: "Fundraising" },
    { name: "Individual & Family Services", value: "Individual & Family Services" },
    { name: "International Trade & Development", value: "International Trade & Development" },
    { name: "Libraries", value: "Libraries" },
    { name: "Museums & Institutions", value: "Museums & Institutions" },
    { name: "Non-Profit Organization Management", value: "Non-Profit Organization Management" },
    { name: "Philanthropy", value: "Philanthropy" },
    { name: "Program Development", value: "Program Development" },
    { name: "Religious Institutions", value: "Religious Institutions" },
    { name: "Think Tanks", value: "Think Tanks" },
    { name: "Software & IT Services", value: "Software & IT Services" },
    { name: "Computer & Network Security", value: "Computer & Network Security" },
    { name: "Computer Software", value: "Computer Software" },
    { name: "Information Technology & Services", value: "Information Technology & Services" },
    { name: "Internet", value: "Internet" },
    { name: "Transportation & Logistics", value: "Transportation & Logistics" },
    { name: "Import & Export", value: "Import & Export" },
    { name: "Logistics & Supply Chain", value: "Logistics & Supply Chain" },
    { name: "Maritime", value: "Maritime" },
    { name: "Package/Freight Delivery", value: "Package/Freight Delivery" },
    { name: "Transportation/Trucking/Railroad", value: "Transportation/Trucking/Railroad" },
    { name: "Warehousing", value: "Warehousing" },
    { name: "Entertainment", value: "Entertainment" },
    { name: "Animation", value: "Animation" },
    { name: "Broadcast Media", value: "Broadcast Media" },
    { name: "Computer Games", value: "Computer Games" },
    { name: "Media Production", value: "Media Production" },
    { name: "Mobile Games", value: "Mobile Games" },
    { name: "Motion Pictures & Film", value: "Motion Pictures & Film" },
    { name: "Music", value: "Music" },
    { name: "Wellness & Fitness", value: "Wellness & Fitness" },
    { name: "Alternative Medicine", value: "Alternative Medicine" },
    { name: "Health, Wellness & Fitness", value: "Health, Wellness & Fitness" },
    { name: "Public Safety", value: "Public Safety" },
    { name: "Law Enforcement", value: "Law Enforcement" },
    { name: "Military", value: "Military" },
    { name: "Public Administration", value: "Public Administration" },
    { name: "Government Administration", value: "Government Administration" },
    { name: "Government Relations", value: "Government Relations" },
    { name: "International Affairs", value: "International Affairs" },
    { name: "Judiciary", value: "Judiciary" },
    { name: "Legislative Office", value: "Legislative Office" },
    { name: "Political Organization", value: "Political Organization" },
    { name: "Public Policy", value: "Public Policy" },
]

const Company = [
  { name: "1-10 employees", value: "1-10 employees" },
  { name: "11-50 employees", value: "11-50 employees" },
  { name: "51-200 employees", value: "51-200 employees" },
  { name: "201-500 employees", value: "201-500 employees" },
  { name: "501-1000 employees", value: "501-1000 employees" },
  { name: "1001-5000 employees", value: "1001-5000 employees" },
  { name: "5001-10,000 employees", value: "5001-10,000 employees" },
  { name: "10,001+ employees", value: "10,001+ employees" },
]
  
export {Industry, Company}